[package]
name = "backend_gh_auth"
version = "0.1.0"
authors = ["Olivier Pinon <oliv.pinon@gmail.com>"]

[dependencies]
rocket = "0.4.0-rc.1"
reqwest = "0.9.4"
toml = "0.4.8"
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"
